# File: similarity/configs.py
CATEGORY_HIERARCHY = {
    "Car": ["Sedan", "Hatchback", "Coupe", "Convertible", "Sports"],
    "SUV": ["Compact_SUV", "Mid-Size_SUV", "Full-Size_SUV", "Crossover"],
    "MPV_Small": ["Compact_MPV", "Minivan"],
    "MPV_Big": ["Large_MPV", "7-Seater_MPV"],
    "Pickup_Truck": ["Regular_Cab", "Extended_Cab", "Crew_Cab"],
    "Bus": ["City_Bus", "Coach", "School_Bus"],
    "Motorcycle": ["Motorbike", "Scooter"],
    "Vans": ["Cargo_Van", "Passenger_Van"],
    "Small_Truck": ["2-Axle_Small", "2-Axle_Big"],
    "Medium_Truck": ["3-Axle_Medium"],
    "Large_Truck": ["4-Axle_Large"],
    "Heavy_Truck": ["5+_Axle_Heavy"],
    "Construction_and_Industrial": ["Bulldozer", "Excavator", "Crane", "Forklift", "Dump_Truck", "Mixer"],
    "Tanker": ["Fuel_Tanker", "Chemical_Tanker", "Gas_Tanker"],
    "Container": ["20ft_Container", "40ft_Container"],
    "Trailer": ["Flatbed_Trailer", "Car_Carrier", "Lowboy_Trailer", "Refrigerator_Trailer"],
    "Unclassified": []
}

CATEGORY_SIMILARITY_GROUPS = {
    ("Car", "SUV"): 0.7,
    ("Car", "MPV_Small"): 0.5,
    ("SUV", "MPV_Small"): 0.6,
    ("SUV", "MPV_Big"): 0.6,
    ("SUV", "Pickup_Truck"): 0.4,
    ("MPV_Small", "MPV_Big"): 0.7,
    ("MPV_Small", "Vans"): 0.5,
    ("MPV_Big", "Vans"): 0.7,
    ("MPV_Small", "Bus"): 0.1,
    ("MPV_Big", "Bus"): 0.1,
    ("Pickup_Truck", "Small_Truck"): 0.6,
    ("Pickup_Truck", "Vans"): 0.2,
    ("Vans", "Small_Truck"): 0.2,
    ("Small_Truck", "Medium_Truck"): 0.8,
    ("Medium_Truck", "Large_Truck"): 0.8,
    ("Large_Truck", "Heavy_Truck"): 0.8,
    ("Small_Truck", "Large_Truck"): 0.5,
    ("Small_Truck", "Heavy_Truck"): 0.4,
    ("Medium_Truck", "Heavy_Truck"): 0.6,
    ("Heavy_Truck", "Construction_and_Industrial"): 0.7,
    ("Heavy_Truck", "Tanker"): 0.6,
    ("Heavy_Truck", "Container"): 0.6,
    ("Heavy_Truck", "Trailer"): 0.5,
    ("Large_Truck", "Construction_and_Industrial"): 0.6,
    ("Large_Truck", "Tanker"): 0.7,
    ("Large_Truck", "Container"): 0.7,
    ("Large_Truck", "Trailer"): 0.6,
    ("Medium_Truck", "Construction_and_Industrial"): 0.4,
    ("Medium_Truck", "Tanker"): 0.5,
    ("Medium_Truck", "Container"): 0.5,
    ("Construction_and_Industrial", "Tanker"): 0.5,
    ("Construction_and_Industrial", "Container"): 0.4,
    ("Construction_and_Industrial", "Trailer"): 0.4,
    ("Tanker", "Container"): 0.6,
    ("Tanker", "Trailer"): 0.5,
    ("Container", "Trailer"): 0.7,
    ("Bus", "Vans"): 0.3,
}

SUBCATEGORY_SIMILARITY_GROUPS = {
    ("Sedan", "Hatchback"): 0.8,
    ("Sedan", "Coupe"): 0.6,
    ("Hatchback", "Coupe"): 0.5,
    ("Coupe", "Sports"): 0.7,
    ("Coupe", "Convertible"): 0.6,
    ("Sports", "Convertible"): 0.5,
    ("Compact_SUV", "Mid-Size_SUV"): 0.8,
    ("Mid-Size_SUV", "Full-Size_SUV"): 0.8,
    ("Compact_SUV", "Full-Size_SUV"): 0.6,
    ("Compact_SUV", "Crossover"): 0.7,
    ("Mid-Size_SUV", "Crossover"): 0.6,
    ("Full-Size_SUV", "Crossover"): 0.4,
    ("Regular_Cab", "Extended_Cab"): 0.8,
    ("Extended_Cab", "Crew_Cab"): 0.8,
    ("Regular_Cab", "Crew_Cab"): 0.6,
    ("City_Bus", "Coach"): 0.6,
    ("City_Bus", "School_Bus"): 0.7,
    ("Coach", "School_Bus"): 0.4,
    ("Cargo_Van", "Passenger_Van"): 0.7,
    ("2-Axle_Small", "2-Axle_Big"): 0.8,
    ("Compact_MPV", "Minivan"): 0.8,
    ("Large_MPV", "7-Seater_MPV"): 0.9,
    ("Fuel_Tanker", "Chemical_Tanker"): 0.7,
    ("Fuel_Tanker", "Gas_Tanker"): 0.8,
    ("Chemical_Tanker", "Gas_Tanker"): 0.6,
    ("20ft_Container", "40ft_Container"): 0.9,
    ("Bulldozer", "Excavator"): 0.6,
    ("Bulldozer", "Dump_Truck"): 0.5,
    ("Excavator", "Crane"): 0.4,
    ("Forklift", "Dump_Truck"): 0.3,
    ("Dump_Truck", "Mixer"): 0.5,
    ("Motorbike", "Scooter"): 0.9,
}

WEIGHTS = {
    'category': 0.25,
    'subcategory': 0.15,
    'country': 0.05,
    'brand': 0.05,
    'model': 0.05,
    'color': 0.05,
    'operator': 0.05,
    'number_of_seats': 0.05,
    'number_of_wheels_visible': 0.05,
    'number_of_axles_inferred': 0.05,
    'number_of_axles_raised': 0.03,
    'truck_trailer_labels_visible': 0.03,
    'cargo_present': 0.03,
    'is_taxi': 0.03,
    'is_bus': 0.03,
    'bus_type': 0.03,
    'is_emergency_vehicle': 0.03,
    'is_electric': 0.03,
}